# Generated by Django 4.2.6 on 2023-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(upload_to='texts/'),
        ),
    ]
