# Generated by Django 4.2.6 on 2023-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_processing', '0002_alter_text_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(null=True, upload_to='files/texts'),
        ),
    ]
