# Generated by Django 4.2.6 on 2023-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_processing', '0003_remove_text_slug_remove_text_title_alter_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
